AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DBInstanceName:
    Type: String
    Description: Name for the RDS instance

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for the RDS instance

  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where the resources will be created

Resources:
  PrimaryDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 50  # Adjust as needed
      DBInstanceIdentifier: !Ref DBInstanceName
      Engine: 'oracle-se2'
      EngineVersion: '19.0.0.0.ru-2023-01.rur-2023-01.r2'  # Adjust as needed
      MasterUsername: admin
      MasterUserPassword: oracle123
      MultiAZ: false  # Set to true for Multi-AZ deployment
      VPCSecurityGroups: [!Ref SecurityGroupId]
      PubliclyAccessible: Yes
      DBSubnetGroupName: b30-db-subnet-group
      DBInstanceClass: db.t3.medium
      LicenseModel: bring-your-own-license

Outputs:
  PrimaryDBEndpoint:
    Description: 'Endpoint of the primary RDS instance'
    Value: !GetAtt PrimaryDBInstance.Endpoint.Address